<a href="https://colab.research.google.com/github/aayushbhurtel/Numerical-Methods/blob/main/BhurtelAayush.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Interpolation ##

here is an updated Gauss-Jordan algorithm for solving system of Linear Equation.

In [ ]:
import numpy as np

def gaussJordan(matrix):
  n = len(matrix)
  for pivot in range(n):
    # Make the pivot element 1
    matrix[pivot, :] = matrix[pivot, :] / matrix[pivot, pivot]

    # Make all other elements in the same column as the pivot element zero
    for row in range(n):
      if row != pivot:
        matrix[row, :] = matrix[row, :] - matrix[row, pivot] * matrix[pivot, :]

  return matrix


lets test the above code to make sure it works:
we're gonna use following as test matrix.


matrix = np.array
([[1, 1, 1],
[0, 1, 1],
[0, 0, 1]])

In [ ]:
matrix = np.array([[1, 1, 1],
                  [0, 1, 1],
                  [0, 0, 1]])

# functn to print
def print_matrix(matrix):
  for row in matrix:
    print(row)
  print()

# printouts
print("Original Matrix:")
print_matrix(matrix)
result1 = gaussJordan(matrix)

print("Reduced Row-Echelon Form Matrix:")
print_matrix(result1)

Original Matrix:
[1 1 1]
[0 1 1]
[0 0 1]

Reduced Row-Echelon Form Matrix:
[1 0 0]
[0 1 0]
[0 0 1]

