<a href="https://colab.research.google.com/github/aayushbhurtel/Numerical-Methods/blob/main/BhurtelAayush_4413_Lesson4_Gauss_Jordan_Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical Method CPSMA 441 Prof: Nicholas Jacobs

Member(s): Hoang Tan Truong, Aakriti Khadka, Aayush Bhurtel

# Project 4: Systems of Linear Equation Solving

This week we will go over Gauss-Jordan and the algorithm to solve it.

# Rows function

Firstly, we need to write methods for operation on rows needed for Jordan-Gauss method, which includes adding, swapping, and multiplying.

Please note that I will make a copy of the matrix list and modify parts needed to be changed instead of appending to a totally new list within the function.

In [ ]:
import math
import numpy as np

matrix = np.array([[3,2,3,1], [6,-4,1,2], [9,-2,4,3]])


#SWAP ROWS

def swap(matrx, r1, r2):
    temp = matrx.copy()
    temp[[r1, r2]] = temp[[r2, r1]]
    return np.array(temp)

swap(matrix, 1, 2)    


array([[ 3,  2,  3,  1],
       [ 9, -2,  4,  3],
       [ 6, -4,  1,  2]])

In [ ]:
#ADD


def addRow(matrx, row, toAdd, multiplier):
    temp = matrx.copy()
    for i in range(len(matrx[row, :])):
        temp[row, i] = temp[row, i] + multiplier*temp[toAdd, i]
    return np.array(temp)

addRow(matrix, 1, 2, 5)


array([[  3,   2,   3,   1],
       [ 51, -14,  21,  17],
       [  9,  -2,   4,   3]])

In [ ]:
def toLeading1(matrx, row, col):
    temp = matrx.copy()
    temp = np.array(temp, float)
    temp[row, :] = temp[row, :]/temp[row, col]
    return np.array(temp)

toLeading1(matrix, 0, 0)
    

array([[ 1.        ,  0.66666667,  1.        ,  0.33333333],
       [ 6.        , -4.        ,  1.        ,  2.        ],
       [ 9.        , -2.        ,  4.        ,  3.        ]])

Next part is to perform these functions on  at least a system of 3 functions and three unknown, which I assume to be the same.

In [ ]:
A = np.array([[2, 3, -1], [1, -1, 1], [3, 4, -2]])

We already have leading zero on row 1, so we can go ahead and skip that step.

In [ ]:
A = addRow(A, 1, 0, -1)
A

array([[ 2,  3, -1],
       [-1, -4,  2],
       [ 3,  4, -2]])

In [ ]:
A = addRow(A, 2, 0, 1)
A

array([[ 2,  3, -1],
       [-1, -4,  2],
       [ 5,  7, -3]])

In [ ]:
A

array([[ 2,  3, -1],
       [-1, -4,  2],
       [ 5,  7, -3]])

In [ ]:
A = toLeading1(A, 1, 1)
A

array([[ 2.  ,  3.  , -1.  ],
       [ 0.25,  1.  , -0.5 ],
       [ 5.  ,  7.  , -3.  ]])

In [ ]:
A = addRow(A, 0, 1, -5)
A

array([[ 0.75, -2.  ,  1.5 ],
       [ 0.25,  1.  , -0.5 ],
       [ 5.  ,  7.  , -3.  ]])

In [ ]:
addRow(A, 2, 1, -2)

array([[ 0.75, -2.  ,  1.5 ],
       [ 0.25,  1.  , -0.5 ],
       [ 4.5 ,  5.  , -2.  ]])

In the next part of the question we create an algorithm for solving systems of equations following the Gauss-Jordan elimination method

In [ ]:
def gauss_jordan(A, b):
    matrix = np.concatenate((A, b.reshape(-1,1)), axis=1)
    rows, cols = matrix.shape
    for j in range(cols-1):
        if not np.any(matrix[j:, j]):
            raise ValueError("System of equations has infinitely many solutions or no solution")
        row_max = np.argmax(np.abs(matrix[j:, j])) + j
        matrix[[j, row_max]] = matrix[[row_max, j]]
        matrix[j, :] = matrix[j, :] / matrix[j, j]
        for i in range(rows):
            if i != j:
                matrix[i, :] = matrix[i, :] - matrix[i, j]*matrix[j, :]
    x = matrix[:, -1]
    return x

# Example system of equations:
# 2x + 3y - z = 1
# x - y + z = 3
# 3x + 4y - 2z = -1

# Converting the equations into matrix form
A = np.array([[2, 3, -1], [1, -1, 1], [3, 4, -2]])
B = np.array([1, 3, -1])

# Solving the above system using Gauss-Jordan elimination
x = gauss_jordan(A, B)
print(x)


[ 1 -1 -2]


(a) Describe your findings in words.


=> Gauss-Jordan elimination method works by transforming the augmented matrix into reduced row-echelon form through series of row operation like swapping, adding and subtracting rows. 
Above program implements the Gauss-Jordan elimination method for solving a system of linear equations in matrix form. It takes two inputs and returns the vector which contains the value of the variables that satisfy the system of equations. Once the augmented matrix is in Reduced Row-Echelon form, the solution vector is the rightmost column of the reduced row-echelon matrix. Above produced code performs these steps in a loop over the columns of matrix.




(b) Discuss the limitations of the algorithm you created. What could you do differently to fix the
issue. Consider what happens with the system
x − 2y = 2
2x − 4y = 4


=> Above algorithm has a time complexity of O(n^3) which is large for systems of equations. This means, algorithm could be extremely slow and expensive. The algorithm could encounter error with singular or ill-conditioned matrices. Singular means the matrix which cannot be inverted. Above code only checks whether the matrices are singular or not, it does not perform checks whether the matrices has no solution. Additional error checking could boost the robustness and reliability of an algorithm.

To fix the above equations and other equations where the matrices may be singular, ill-conditioned, or inconsistent, implement partial pivoting. Partial pivoting involves selecting the maximum pivot element in each column to reduce the potential for division by very small numbers and minimize round-off errors. This can help improve the numerical stability of the algorithm. User more efficient and effective alogrithm such as LU or QR decomposition.